### PR TITLE
Check for 'wget' prerequisite instead of falling over

### PR DESCRIPTION
**Pull request by reecebenson**

### CODE REVIEW

**Comment by andrewdetorres** [comment]
Check for wget command success already implemented between 35-49 (57-67 on your PR). Happy for this to be changed to the new prerequisite check if the following lines are adjusted to avoid a double check.

```
  # Download Bootstrap 3 for Drupal 8
  wget https://ftp.drupal.org/files/projects/bootstrap-8.x-3.21.tar.gz;

  # Check to see if command was successful
  if [ $? -eq 0 ]; then
    printf "${GR}wget actioned successfully${NC}\n\n"
  else
    printf "${RED}wget command not executed by d8b3, please use the following to install wget\n\n${NC}"
    printf "For MacOS please run:\n\n";
    printf "    brew install wget\n\n";
    printf "For Linux please run:\n\n";
    printf "    apt-get install wget\n\n";
    printf "Alternatively, please visit ${GR}https://npmjs.com/package/d8b3${NC} for more information.\n\n";
    exit 1;
  fi
```

**Comment by reecebenson** [comment]
I've removed the previous failcheck for `wget` as it becomes pointless with this addition. You won't be able to proceed from the prerequisites check if `wget` is not installed.

**Comment by andrewdetorres** [comment]
colouring error on line 95 with the last NC tag. 

Please change from ```{$NC}``` to ```${NC}```

see
```95: printf "${NC}Error:\n${RED}- Please make sure to install the above failed requirements.{$NC}\n\n"```

**Comment by andrewdetorres** [comment]
Thanks Reece 😄

**Pull request merged**
